services:
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
    env_file: .env
    configs:
      - source: rabbitmq-plugins
        target: /etc/rabbitmq/enabled_plugins
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq

  rss-fetcher:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: rss-fetcher
    restart: unless-stopped
    env_file: .env
    environment:
      - APP_ENV=production
    depends_on:
      - rabbitmq

  queue-worker:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: queue-worker
    restart: unless-stopped
    env_file: .env
    environment:
      - APP_ENV=production
    depends_on:
      - rabbitmq

configs:
  rabbitmq-plugins:
    content: "[rabbitmq_management]."

volumes:
  rabbitmq-lib:
    driver: local
  rabbitmq-log:
    driver: local


